## @file
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

trigger:
- dev/*
- release/*

pr:
- dev/*
- release/*

schedules:
- cron: "30 9 * * 0,3"  # Sun/Wed at 2:30AM Pacific
  displayName: Sun/Wed Build
  branches:
    include:
    - dev/*
    - release/*
  always: true          # Always build, even if no changes

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: IA32,X64,ARM,AARCH64
    do_ci_build: true
    do_ci_setup: true
    do_non_ci_setup: true
    extra_steps:
    - script: sudo apt-get install mingw-w64
      displayName: Install Windows Resource Compiler for Linux
    packages: OemPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: GCC5
    vm_image: ubuntu-latest

